### PR TITLE
Add mirrord teams waitlist signup command

### PR DESCRIPTION
**Pull request by DmitryDodzin**
closes metalbear-co/mirrord#1503 & metalbear-co/mirrord#1306

### CODE REVIEW

**Comment by Razz4780** [comment]
Will this be visible to the users? Maybe we should also add a popup or sth

**Comment by eyalb181** [comment]
> Will this be visible to the users? Maybe we should also add a popup or sth

Indeed, see https://github.com/metalbear-co/mirrord/issues/1306 for the planned changes

**Comment by eyalb181** [comment]
@DmitryDodzin General note - if I click "Show deployments", I expect deployments to show next time I run mirrord, rather than pods again

**Comment by DmitryDodzin** [comment]
I used lastTarget to determine when to show deployments or pods next time it is run

**Review by eyalb181 — CHANGES_REQUESTED** [review]

**Review by eyalb181 — APPROVED** [review]

**Pull request merged**
